-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lucifron", {
	[19702] = "red",
	[19703] = {"green","yellow"},
	[20604] = {"blue","orange"},
})

BigWigs:AddSounds("Lucifron", {
	[19702] = "long",
	[19703] = "info",
})

BigWigs:AddColors("Magmadar", {
	[19408] = "orange",
	[19428] = "blue",
	[19451] = {"green","yellow"},
	[461131] = "cyan",
})

BigWigs:AddSounds("Magmadar", {
	[19408] = "long",
	[19428] = "underyou",
	[19451] = "info",
	[461131] = "alert",
})

BigWigs:AddColors("Gehennas", {
	[19716] = {"green","orange"},
	[19717] = "blue",
})

BigWigs:AddSounds("Gehennas", {
	[19717] = "underyou",
})

BigWigs:AddColors("Garr", {
	[19492] = {"red","yellow"},
})

BigWigs:AddSounds("Garr", {
	[19492] = "info",
})

BigWigs:AddColors("Baron Geddon", {
	[19659] = {"green","yellow"},
	[19695] = "red",
	[20475] = {"blue","orange","red"},
	[20478] = "orange",
	[461103] = "blue",
})

BigWigs:AddSounds("Baron Geddon", {
	[19659] = "info",
	[19695] = "alarm",
	[20475] = "warning",
	[20478] = "long",
	[461103] = "underyou",
})

BigWigs:AddColors("Shazzrah", {
	[19713] = "yellow",
	[19714] = {"green","orange"},
	[19715] = "yellow",
	[23138] = "red",
	[460856] = {"green","red"},
})

BigWigs:AddSounds("Shazzrah", {
	[19713] = "alarm",
	[19714] = "alarm",
	[19715] = "alert",
	[23138] = "long",
	[460856] = {"info","warning"},
})

BigWigs:AddColors("Sulfuron Harbinger", {
	[19775] = "red",
	[19778] = "orange",
	[19779] = "yellow",
	[461103] = "blue",
})

BigWigs:AddSounds("Sulfuron Harbinger", {
	[19775] = "alert",
	[19778] = "alarm",
	[19779] = "info",
	[461103] = "underyou",
})

BigWigs:AddColors("Golemagg the Incinerator", {
	[13880] = {"blue","purple"},
	[20228] = {"blue","orange"},
	[460858] = {"blue","orange"},
	[461463] = "red",
})

BigWigs:AddSounds("Golemagg the Incinerator", {
	[13880] = "alert",
	[460858] = "alarm",
	[461463] = "warning",
})

BigWigs:AddColors("Majordomo Executus", {
	[20534] = {"blue","yellow"},
	[20619] = "red",
	[21075] = "yellow",
	[364895] = "orange",
	[364908] = "orange",
	[461056] = {"blue","red"},
})

BigWigs:AddSounds("Majordomo Executus", {
	[20619] = "info",
	[21075] = "info",
	[364895] = "alert",
	[364908] = "alert",
	[461056] = "warning",
})

BigWigs:AddColors("Ragnaros Classic", {
	[20566] = "red",
	[461062] = "blue",
	["adds"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ragnaros Classic", {
	[20566] = "info",
	[461062] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("The Molten Core", {
	[460883] = "red",
	[460885] = "red",
	[460887] = "orange",
	[460895] = {"blue","yellow"},
	[460898] = {"blue","yellow"},
	["adds"] = "cyan",
})

BigWigs:AddSounds("The Molten Core", {
	[460883] = "alert",
	[460885] = "long",
	[460887] = "alarm",
	[460895] = "warning",
	[460898] = "warning",
	["adds"] = "info",
})

BigWigs:AddColors("Razorgore the Untamed", {
	[14515] = {"blue","red"},
	[23023] = {"blue","orange"},
	[366909] = "blue",
	[367740] = "blue",
	[367873] = "blue",
	["adds"] = "cyan",
	["eggs"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Razorgore the Untamed", {
	[14515] = "alert",
	[23023] = "info",
	[366909] = "underyou",
	[367740] = "alarm",
	[367873] = "underyou",
	["adds"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Vaelastrasz the Corrupt", {
	[18173] = {"blue","yellow"},
	[23620] = {"blue","purple"},
})

BigWigs:AddSounds("Vaelastrasz the Corrupt", {
	[18173] = "warning",
	[23620] = {"long","warning"},
})

BigWigs:AddColors("Broodlord Lashlayer", {
	[18670] = {"blue","yellow"},
	[23331] = "orange",
	[24573] = {"blue","purple"},
	[367369] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Broodlord Lashlayer", {
	[18670] = "alert",
	[23331] = "info",
	[24573] = "alarm",
	[367369] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Firemaw", {
	[22539] = "red",
	[23339] = "yellow",
	[23341] = "blue",
	[366305] = "blue",
})

BigWigs:AddSounds("Firemaw", {
	[22539] = "long",
	[23339] = "info",
	[23341] = "warning",
	[366305] = "warning",
})

BigWigs:AddColors("Ebonroc", {
	[22539] = "red",
	[23339] = "yellow",
	[23340] = {"blue","purple"},
	[368515] = "blue",
})

BigWigs:AddSounds("Ebonroc", {
	[22539] = "long",
	[23339] = "info",
	[23340] = "alarm",
	[368515] = "alert",
})

BigWigs:AddColors("Flamegor", {
	[22539] = "red",
	[23339] = "yellow",
	[23342] = {"green","orange"},
	[368521] = "blue",
	[467732] = "blue",
	[467764] = "blue",
})

BigWigs:AddSounds("Flamegor", {
	[22539] = "long",
	[23339] = "info",
	[23342] = "alarm",
	[368521] = "alert",
	[467732] = "warning",
	[467764] = "warning",
})

BigWigs:AddColors("Chromaggus", {
	[23128] = {"green","orange"},
	[23170] = "blue",
	[23174] = "red",
	[23537] = "red",
	[468195] = "cyan",
	["breath"] = "yellow",
	["vulnerability"] = {"green","red"},
})

BigWigs:AddSounds("Chromaggus", {
	[23128] = "alarm",
	[23174] = "warning",
	[468195] = "long",
	["breath"] = "long",
	["vulnerability"] = {"info","warning"},
})

BigWigs:AddColors("Nefarian Classic", {
	[22539] = "yellow",
	[22667] = {"blue","yellow"},
	[22686] = "red",
	[22687] = {"blue","green","yellow"},
	["add"] = "green",
	["classcall"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nefarian Classic", {
	[22539] = "alarm",
	[22667] = "warning",
	[22686] = "alert",
	[22687] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Blackwing Lair Trash", {
	[19717] = "blue",
	[22291] = {"blue","orange"},
	[369330] = "blue",
	[466357] = {"blue","orange"},
	[466435] = {"blue","orange"},
	["target_vulnerability"] = {"red","yellow"},
})

BigWigs:AddSounds("Blackwing Lair Trash", {
	[19717] = "underyou",
	[22291] = "warning",
	[369330] = "underyou",
	[466357] = "warning",
	[466435] = "warning",
})

BigWigs:AddColors("Kurinnaxx", {
	[25646] = {"blue","purple"},
	[25648] = {"blue","orange"},
	[26527] = {"green","red"},
})

BigWigs:AddSounds("Kurinnaxx", {
	[25646] = "warning",
	[25648] = "alert",
	[26527] = "long",
})

BigWigs:AddColors("General Rajaxx", {
	[8269] = "red",
	[25462] = {"green","orange"},
	[25471] = {"blue","yellow"},
	[25599] = "orange",
	[26550] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("General Rajaxx", {
	[8269] = "long",
	[25462] = "alarm",
	[25471] = "warning",
	[25599] = "alert",
	[26550] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("Moam", {
	[25685] = {"red","yellow"},
})

BigWigs:AddSounds("Moam", {
	[25685] = "long",
})

BigWigs:AddColors("Buru the Gorger", {
	["fixate"] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Buru the Gorger", {
	["fixate"] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Ayamiss the Hunter", {
	[8269] = {"green","red"},
	[17742] = "blue",
	[25725] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ayamiss the Hunter", {
	[17742] = "underyou",
	[25725] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Ossirian the Unscarred", {
	[25176] = "red",
	[25177] = "yellow",
	[25178] = "yellow",
	[25180] = "yellow",
	[25181] = "yellow",
	[25183] = "yellow",
	[25188] = "orange",
	[25189] = {"blue","red"},
	[25195] = "orange",
})

BigWigs:AddSounds("Ossirian the Unscarred", {
	[25176] = "alert",
	[25177] = "info",
	[25178] = "info",
	[25180] = "info",
	[25181] = "info",
	[25183] = "info",
	[25189] = "warning",
	[25195] = "long",
})

BigWigs:AddColors("Ruins of Ahn'Qiraj Trash", {
	[8269] = "red",
	[8732] = "orange",
	[14297] = "red",
	[17430] = "green",
	[17431] = "green",
	[22997] = {"blue","yellow"},
	[24340] = "red",
	[25698] = "orange",
	[1214956] = "yellow",
	[1215202] = "blue",
	[1215421] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ruins of Ahn'Qiraj Trash", {
	[8269] = "long",
	[8732] = "alert",
	[14297] = "alarm",
	[22997] = "warning",
	[24340] = "info",
	[25698] = "long",
	[1215202] = "warning",
	[1215421] = "underyou",
})

BigWigs:AddColors("The Prophet Skeram", {
	[747] = "cyan",
	[785] = {"blue","yellow"},
	[20449] = "red",
	[26192] = "orange",
})

BigWigs:AddSounds("The Prophet Skeram", {
	[747] = "info",
	[785] = "alert",
	[20449] = "alert",
})

BigWigs:AddColors("Silithid Royalty", {
	[25786] = "blue",
	[25807] = {"green","orange"},
	[25812] = "yellow",
	[26580] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Silithid Royalty", {
	[25786] = "underyou",
	[25807] = "alert",
	[25812] = "info",
	[26580] = "long",
})

BigWigs:AddColors("Battleguard Sartura", {
	[8269] = "orange",
	[26083] = {"green","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Battleguard Sartura", {
	[8269] = "long",
	[26083] = "warning",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Fankriss the Unyielding", {
	[720] = {"blue","red"},
	[25646] = {"blue","purple"},
	[25832] = "cyan",
})

BigWigs:AddSounds("Fankriss the Unyielding", {
	[720] = "alarm",
	[25646] = "alert",
	[25832] = "warning",
})

BigWigs:AddColors("Viscidus", {
	[25989] = "blue",
	[25991] = "yellow",
	["freeze"] = {"green","orange","red"},
})

BigWigs:AddSounds("Viscidus", {
	[25989] = "underyou",
})

BigWigs:AddColors("Princess Huhuran", {
	[26051] = {"green","yellow"},
	[26180] = {"green","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Princess Huhuran", {
	[26051] = "alarm",
	[26180] = "alert",
	["berserk"] = {"alarm","long"},
})

BigWigs:AddColors("The Twin Emperors", {
	[800] = "orange",
	[802] = "yellow",
	[804] = "red",
	[7393] = "red",
	[26607] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("The Twin Emperors", {
	[800] = "alert",
	[802] = "info",
	[804] = "alarm",
	[7393] = "warning",
	[26607] = "underyou",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Ouro", {
	[26102] = "red",
	[26103] = "orange",
	[26615] = {"green","yellow"},
	[1215744] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ouro", {
	[26102] = "alert",
	[26103] = "alarm",
	[26615] = "info",
	[1215744] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("C'Thun", {
	[26029] = {"orange","red"},
	[26134] = "blue",
	[26476] = "blue",
	["eye_tentacles"] = "red",
	["giant_claw_tentacle"] = "red",
	["giant_eye_tentacle"] = "red",
	["stages"] = "cyan",
	["weakened"] = "green",
})

BigWigs:AddSounds("C'Thun", {
	[26134] = "warning",
	[26476] = "warning",
	["eye_tentacles"] = "alarm",
	["giant_claw_tentacle"] = "alert",
	["giant_eye_tentacle"] = "warning",
	["stages"] = {"alert","long"},
	["weakened"] = "long",
})

BigWigs:AddColors("Ahn'Qiraj Trash", {
	[8269] = "red",
	[8599] = "red",
	[17430] = "green",
	[17431] = "green",
	[25051] = {"blue","purple"},
	[25698] = "orange",
	[26079] = {"blue","yellow"},
	[26554] = "orange",
	[26555] = "red",
	[26556] = {"blue","yellow"},
	[26558] = "red",
	[26565] = "orange",
	[1214956] = "yellow",
	[1215202] = "blue",
	[1215421] = "blue",
	["stages"] = "cyan",
	["target_buffs"] = {"red","yellow"},
})

BigWigs:AddSounds("Ahn'Qiraj Trash", {
	[8269] = "long",
	[25698] = "long",
	[26079] = "alert",
	[26554] = "alert",
	[26555] = "alarm",
	[26556] = "warning",
	[26558] = "info",
	[26565] = "info",
	[1215202] = "warning",
	[1215421] = "underyou",
})

BigWigs:AddColors("High Priestess Jeklik", {
	[12097] = {"blue","purple"},
	[16098] = {"green","red"},
	[23952] = {"blue","orange"},
	[23953] = {"green","yellow"},
	[23954] = {"green","red"},
	[23970] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Priestess Jeklik", {
	[16098] = "warning",
	[23953] = "alert",
	[23954] = "warning",
	[23970] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("High Priest Venoxis", {
	[8269] = "orange",
	[23860] = "yellow",
	[23861] = {"blue","red"},
	[23865] = {"blue","yellow"},
	[23895] = {"green","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Priest Venoxis", {
	[8269] = "long",
	[23861] = {"alarm","underyou"},
	[23895] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("High Priestess Mar'li", {
	[24083] = "yellow",
	[24099] = "yellow",
	[24300] = {"blue","orange"},
})

BigWigs:AddSounds("High Priestess Mar'li", {
	[24083] = "info",
	[24099] = "alarm",
	[24300] = "alert",
})

BigWigs:AddColors("High Priest Thekal", {
	[8269] = "red",
	[12540] = {"blue","purple"},
	[21060] = {"blue","purple"},
	[22666] = {"blue","yellow"},
	[22859] = {"blue","purple"},
	[24183] = "yellow",
	[24185] = "orange",
	[24189] = "orange",
	[24208] = "red",
})

BigWigs:AddSounds("High Priest Thekal", {
	[8269] = "alarm",
	[12540] = "warning",
	[21060] = "warning",
	[22666] = "alert",
	[22859] = "alarm",
	[24183] = "info",
	[24185] = "alert",
	[24208] = "alert",
})

BigWigs:AddColors("High Priestess Arlokk", {
	[12540] = {"blue","purple"},
	[24210] = {"blue","red"},
	[24212] = {"blue","orange"},
})

BigWigs:AddSounds("High Priestess Arlokk", {
	[12540] = "warning",
	[24210] = "alarm",
	[24212] = "alert",
})

BigWigs:AddColors("Hakkar", {
	[24324] = {"orange","red"},
	[24327] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Hakkar", {
	[24324] = {"alarm","long"},
	[24327] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Bloodlord Mandokir", {
	[16856] = {"blue","purple"},
	[24314] = {"blue","yellow"},
	[24318] = {"blue","red"},
})

BigWigs:AddSounds("Bloodlord Mandokir", {
	[16856] = "warning",
	[24314] = "info",
	[24318] = "alarm",
})

BigWigs:AddColors("Jin'do the Hexxer", {
	[17172] = {"blue","purple"},
	[24262] = "red",
	[24306] = {"blue","yellow"},
	[24309] = "orange",
	[24466] = {"blue","yellow"},
})

BigWigs:AddSounds("Jin'do the Hexxer", {
	[17172] = "alert",
	[24262] = "warning",
	[24306] = "alarm",
	[24309] = "info",
	[24466] = "long",
})

BigWigs:AddColors("Gahz'ranka", {
	[21099] = "yellow",
	[22421] = "orange",
})

BigWigs:AddSounds("Gahz'ranka", {
	[21099] = "info",
	[22421] = "alarm",
})

BigWigs:AddColors("Edge of Madness", {
	[24646] = "orange",
	[24699] = "orange",
	[24729] = "orange",
	[26550] = "yellow",
})

BigWigs:AddSounds("Edge of Madness", {
	[24646] = "alarm",
	[24699] = "alert",
	[24729] = "alarm",
	[26550] = "info",
})

BigWigs:AddColors("Patchwerk", {
	[28131] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Patchwerk", {
	[28131] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Grobbulus", {
	[28169] = {"blue","red"},
	[28240] = "yellow",
	["adds"] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Grobbulus", {
	[28169] = "warning",
	[28240] = "info",
	["adds"] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Gluth", {
	[25646] = {"blue","purple"},
	[28371] = {"green","orange"},
	[28375] = "red",
	[29306] = "blue",
	[29685] = "yellow",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Gluth", {
	[25646] = "info",
	[28371] = "alert",
	[28375] = "warning",
	[29685] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Thaddius", {
	[28059] = "blue",
	[28084] = "blue",
	[28089] = "orange",
	[28134] = "red",
	[28338] = "red",
	["berserk"] = {"orange","red"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Thaddius", {
	[28059] = "warning",
	[28084] = "warning",
	[28089] = "long",
	[28338] = "alert",
	["berserk"] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Noth the Plaguebringer", {
	[29208] = "yellow",
	[29212] = "blue",
	[29213] = {"green","red"},
	[29214] = "red",
	["adds"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Noth the Plaguebringer", {
	[29208] = "alert",
	[29213] = "warning",
	[29214] = "alarm",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Heigan the Unclean", {
	[29998] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Heigan the Unclean", {
	[29998] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Loatheb", {
	[29184] = "blue",
	[29204] = "red",
	[29232] = "blue",
	[29234] = "red",
	[29865] = "yellow",
	[30281] = "orange",
	[1225419] = "blue",
})

BigWigs:AddSounds("Loatheb", {
	[29184] = "long",
	[29204] = "warning",
	[29234] = "info",
	[30281] = "alert",
	[1225419] = "long",
})

BigWigs:AddColors("Anub'Rekhan", {
	[28783] = {"blue","yellow"},
	[28785] = {"green","orange","red","yellow"},
})

BigWigs:AddSounds("Anub'Rekhan", {
	[28783] = {"alert","warning"},
	[28785] = {"info","long"},
})

BigWigs:AddColors("Grand Widow Faerlina", {
	[28732] = "yellow",
	[28794] = "blue",
	[28796] = "orange",
	[28798] = {"green","red"},
	[30225] = "blue",
})

BigWigs:AddSounds("Grand Widow Faerlina", {
	[28732] = "info",
	[28794] = "underyou",
	[28796] = "alert",
	[28798] = "warning",
})

BigWigs:AddColors("Maexxna", {
	[28622] = {"blue","yellow"},
	[28747] = "orange",
	[28776] = {"blue","green","purple"},
	[29484] = "red",
	["adds"] = "yellow",
})

BigWigs:AddSounds("Maexxna", {
	[28622] = "alert",
	[28747] = "warning",
	[28776] = "info",
	[29484] = "long",
})

BigWigs:AddColors("Instructor Razuvious", {
	[29060] = "orange",
	[29061] = "yellow",
	[29107] = "red",
})

BigWigs:AddSounds("Instructor Razuvious", {
	[29060] = "info",
	[29061] = "long",
	[29107] = "warning",
})

BigWigs:AddColors("Gothik the Harvester", {
	["add_death"] = "green",
	["adds"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Gothik the Harvester", {
	["stages"] = {"info","long"},
})

BigWigs:AddColors("The Four Horsemen", {
	[28863] = {"blue","orange"},
	[28883] = "yellow",
	[28884] = "red",
	[29061] = "yellow",
	["mark"] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Four Horsemen", {
	[28863] = {"alarm","underyou"},
	[28883] = "alert",
	[28884] = "info",
	[29061] = "long",
	["mark"] = "warning",
})

BigWigs:AddColors("Sapphiron", {
	[28522] = {"blue","yellow"},
	[28524] = "red",
	[28542] = {"green","orange"},
	[28547] = "blue",
	[1219728] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Sapphiron", {
	[28524] = "warning",
	[28542] = "alert",
	[28547] = "underyou",
	[1219728] = "warning",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Kel'Thuzad", {
	[27808] = {"blue","yellow"},
	[27810] = {"blue","red"},
	[27819] = {"blue","yellow"},
	[28410] = {"blue","orange"},
	[28467] = {"blue","purple"},
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kel'Thuzad", {
	[27808] = "alert",
	[27810] = "warning",
	[27819] = "warning",
	[28410] = "long",
	["adds"] = "info",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Naxxramas Trash", {
	[1219235] = {"blue","yellow"},
})

BigWigs:AddSounds("Naxxramas Trash", {
	[1219235] = "warning",
})

BigWigs:AddColors("Onyxia", {
	[17086] = "red",
	[18392] = {"blue","yellow"},
	[18431] = "yellow",
	[18435] = "orange",
	[18958] = {"blue","purple"},
	[364849] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Onyxia", {
	[17086] = "warning",
	[18392] = "alarm",
	[18431] = "info",
	[18435] = "alert",
	[364849] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Azuregos", {
	[21097] = "orange",
	[21099] = "orange",
	[21147] = "yellow",
	[22067] = {"green","red"},
})

BigWigs:AddSounds("Azuregos", {
	[21097] = "alert",
	[21099] = "alert",
	[21147] = "alarm",
	[22067] = {"info","warning"},
})

BigWigs:AddColors("Lord Kazzak", {
	[21056] = {"blue","yellow"},
	[21063] = {"blue","orange"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Lord Kazzak", {
	[21056] = "warning",
	[21063] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Emeriss", {
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
	[24871] = "blue",
	[24910] = "red",
	[24928] = {"blue","orange"},
})

BigWigs:AddSounds("Emeriss", {
	[24814] = "info",
	[24818] = "warning",
	[24871] = "underyou",
	[24910] = {"alarm","long"},
	[24928] = "alert",
})

BigWigs:AddColors("Lethon", {
	[24811] = "red",
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
	[24821] = "yellow",
})

BigWigs:AddSounds("Lethon", {
	[24811] = "long",
	[24814] = "info",
	[24818] = "warning",
	[24821] = "alert",
})

BigWigs:AddColors("Taerar", {
	[22686] = "orange",
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
	[24841] = "cyan",
})

BigWigs:AddSounds("Taerar", {
	[24814] = "info",
	[24818] = "warning",
	[24841] = "long",
})

BigWigs:AddColors("Ysondre", {
	[24795] = "cyan",
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
})

BigWigs:AddSounds("Ysondre", {
	[24795] = "long",
	[24814] = "info",
	[24818] = "warning",
})

BigWigs:AddColors("Baron Aquanis Discovery", {
	[404806] = {"blue","yellow"},
	[405953] = "blue",
	[413664] = "orange",
})

BigWigs:AddSounds("Baron Aquanis Discovery", {
	[404806] = "warning",
	[405953] = "underyou",
	[413664] = "long",
})

BigWigs:AddColors("Ghamoo-ra Discovery", {
	[406970] = "orange",
	[407025] = {"red","yellow"},
	[407077] = "purple",
	[407095] = {"blue","purple"},
})

BigWigs:AddSounds("Ghamoo-ra Discovery", {
	[406970] = "warning",
	[407025] = {"info","long"},
	[407095] = "alert",
})

BigWigs:AddColors("Lady Sarevess Discovery", {
	[367741] = {"blue","green","red"},
	[407568] = {"blue","orange"},
	[407653] = {"blue","yellow"},
	[407791] = {"blue","green","red"},
})

BigWigs:AddSounds("Lady Sarevess Discovery", {
	[367741] = "alarm",
	[407568] = {"alert","underyou"},
	[407653] = "warning",
	[407791] = "alarm",
})

BigWigs:AddColors("Gelihast Discovery", {
	[411956] = {"blue","yellow"},
	[411959] = {"blue","red"},
	[412072] = {"blue","purple"},
	[412456] = "cyan",
})

BigWigs:AddSounds("Gelihast Discovery", {
	[411956] = "alert",
	[411959] = "alert",
	[412072] = "warning",
	[412456] = "long",
})

BigWigs:AddColors("Lorgus Jett Discovery", {
	[22883] = {"green","orange"},
	[414691] = "yellow",
	[414763] = "red",
	[419636] = "orange",
	[419649] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Lorgus Jett Discovery", {
	[22883] = "alert",
	[414691] = "alert",
	[414763] = "warning",
	[419636] = "info",
})

BigWigs:AddColors("Twilight Lord Kelris Discovery", {
	[423135] = {"blue","yellow"},
	[425265] = {"blue","green","orange","red"},
	[425460] = "blue",
	[426489] = {"blue","cyan"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Twilight Lord Kelris Discovery", {
	[425265] = {"alert","info"},
	[425460] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Aku'mai Discovery", {
	[427625] = {"blue","green"},
	[428482] = {"blue","green"},
	[429168] = "red",
	[429356] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Aku'mai Discovery", {
	[427625] = "alarm",
	[428482] = "alarm",
	[429168] = "warning",
	[429356] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Grubbis Discovery", {
	[3019] = {"green","red"},
	[434168] = "cyan",
	[434724] = {"blue","yellow"},
	[434941] = "orange",
	[436027] = "yellow",
	[436059] = "yellow",
	[436074] = {"green","red"},
	[436100] = {"blue","green","orange","yellow"},
	[439956] = "orange",
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Grubbis Discovery", {
	[434941] = "info",
	[436027] = "long",
	[436059] = "long",
	[436074] = "alarm",
	[436100] = {"alert","warning"},
	[439956] = "warning",
	["adds"] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Viscous Fallout Discovery", {
	[433546] = "orange",
	[434358] = "cyan",
	[434434] = {"blue","red"},
})

BigWigs:AddSounds("Viscous Fallout Discovery", {
	[433546] = {"info","warning"},
	[434358] = "long",
	[434434] = {"alarm","underyou"},
})

BigWigs:AddColors("Crowd Pummeler 9-60 Discovery", {
	[431839] = "blue",
	[432062] = {"blue","yellow"},
	[432423] = "orange",
})

BigWigs:AddSounds("Crowd Pummeler 9-60 Discovery", {
	[432062] = "alarm",
	[432423] = "warning",
})

BigWigs:AddColors("Electrocutioner 6000 Discovery", {
	[433251] = {"blue","red"},
	[433359] = {"blue","yellow"},
	[433398] = "orange",
})

BigWigs:AddSounds("Electrocutioner 6000 Discovery", {
	[433251] = "warning",
	[433359] = "alarm",
	[433398] = "info",
})

BigWigs:AddColors("Mechanical Menagerie Discovery", {
	[436570] = "orange",
	[436692] = "cyan",
	[436695] = "red",
	[436816] = {"blue","yellow"},
	[436825] = {"green","red"},
	[436833] = "orange",
	[436836] = "yellow",
	[438735] = "blue",
	[440073] = {"blue","cyan"},
	["run"] = "blue",
})

BigWigs:AddSounds("Mechanical Menagerie Discovery", {
	[436692] = "info",
	[436695] = "warning",
	[436816] = "alarm",
	[436833] = "alert",
	[436836] = {"info","long"},
	[438735] = "long",
	[440073] = "long",
})

BigWigs:AddColors("Mekgineer Thermaplugg Discovery", {
	[437853] = "cyan",
	[438683] = "purple",
	[438710] = {"blue","orange"},
	[438713] = "yellow",
	[438719] = "purple",
	[438720] = {"blue","orange"},
	[438723] = "yellow",
	[438726] = "purple",
	[438727] = {"blue","orange"},
	[438732] = {"green","yellow"},
	[438735] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Mekgineer Thermaplugg Discovery", {
	[437853] = "info",
	[438683] = "alarm",
	[438713] = "alert",
	[438719] = "alarm",
	[438723] = "alert",
	[438726] = "alarm",
	[438732] = "alert",
	[438735] = "long",
})

BigWigs:AddColors("Atal'alarion Discovery", {
	[437503] = "yellow",
	[437597] = "red",
})

BigWigs:AddSounds("Atal'alarion Discovery", {
	[437503] = "info",
	[437597] = "warning",
})

BigWigs:AddColors("Festering Rotslime Discovery", {
	[438136] = "blue",
	[438142] = {"green","yellow"},
})

BigWigs:AddSounds("Festering Rotslime Discovery", {
	[438136] = "underyou",
	[438142] = "alert",
})

BigWigs:AddColors("Atal'ai Defenders Discovery", {
	[23511] = "red",
	[438294] = "orange",
	[438335] = "red",
	[438341] = {"green","red"},
	[438350] = "red",
	[445284] = {"blue","yellow"},
	[445289] = "orange",
	[446338] = "red",
	[446360] = "orange",
	[446364] = {"green","yellow"},
	[446372] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Atal'ai Defenders Discovery", {
	[23511] = "warning",
	[438335] = "alert",
	[438341] = "warning",
	[438350] = "warning",
	[445289] = "alarm",
	[446338] = "warning",
	[446360] = "alarm",
	[446364] = "alert",
	[446372] = "long",
	["stages"] = "info",
})

BigWigs:AddColors("Dreamscythe and Weaver Discovery", {
	[442622] = {"blue","purple"},
	[443766] = "yellow",
	[443856] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Dreamscythe and Weaver Discovery", {
	[442622] = "alert",
	[443766] = "info",
	[443856] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("Jammal'an and Ogom Discovery", {
	[437809] = "yellow",
	[437817] = "red",
	[437847] = {"blue","orange"},
	[437868] = {"green","red"},
	[437921] = "orange",
	[437927] = "red",
	[437928] = "yellow",
	[437930] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Jammal'an and Ogom Discovery", {
	[437809] = "alarm",
	[437817] = "warning",
	[437847] = "info",
	[437868] = "alert",
	[437921] = "alert",
	[437927] = "alarm",
	[437928] = "long",
	[437930] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Morphaz and Hazzas Discovery", {
	[446468] = "orange",
	[446487] = {"blue","purple"},
	[446489] = "red",
	[446661] = "cyan",
})

BigWigs:AddSounds("Morphaz and Hazzas Discovery", {
	[446468] = "alert",
	[446487] = "alert",
	[446489] = "alarm",
	[446661] = "info",
})

BigWigs:AddColors("Shade of Eranikus Discovery", {
	[3391] = "purple",
	[437301] = "cyan",
	[437324] = {"blue","green"},
	[437353] = {"blue","purple"},
	[437390] = {"blue","green","yellow"},
	[437398] = "orange",
	[437416] = "cyan",
	[445498] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Shade of Eranikus Discovery", {
	[3391] = "info",
	[437301] = "info",
	[437324] = {"alarm","info"},
	[437353] = {"alarm","alert"},
	[437390] = {"alarm","alert","info"},
	[437398] = "warning",
	[437416] = "long",
	[445498] = "warning",
})

BigWigs:AddColors("Avatar of Hakkar Discovery", {
	[443953] = "blue",
	[443990] = {"green","red"},
	[444039] = {"blue","red"},
	[444046] = {"green","orange"},
	[444132] = "yellow",
	[444255] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Avatar of Hakkar Discovery", {
	[443953] = "underyou",
	[443990] = "warning",
	[444039] = "warning",
	[444046] = "alarm",
	[444132] = "long",
	[444255] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Lord Kazzak Season of Discovery", {
	[21056] = {"blue","green","red","yellow"},
	[21063] = {"blue","green","orange"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Lord Kazzak Season of Discovery", {
	[21056] = {"long","warning"},
	[21063] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Azuregos Season of Discovery", {
	[21097] = "orange",
	[21099] = "orange",
	[21147] = "yellow",
	[22067] = {"green","red"},
})

BigWigs:AddSounds("Azuregos Season of Discovery", {
	[21097] = "alert",
	[21099] = "alert",
	[21147] = "alarm",
	[22067] = {"info","warning"},
})

BigWigs:AddColors("Thunderaan Season of Discovery", {
	[11642] = {"green","orange"},
	[465700] = {"blue","red"},
	[466211] = {"blue","purple"},
	[466774] = "yellow",
	[470866] = "blue",
})

BigWigs:AddSounds("Thunderaan Season of Discovery", {
	[11642] = "alert",
	[465700] = "warning",
	[466211] = "alarm",
	[466774] = "info",
	[470866] = "underyou",
})

BigWigs:AddColors("Emeriss Season of Discovery", {
	[24814] = "green",
	[24910] = "red",
	[1213155] = {"blue","orange"},
	[1213169] = "blue",
	[1213170] = {"blue","purple","yellow"},
})

BigWigs:AddSounds("Emeriss Season of Discovery", {
	[24814] = "info",
	[24910] = {"alarm","long"},
	[1213155] = "alert",
	[1213169] = "underyou",
	[1213170] = "warning",
})

BigWigs:AddColors("Lethon Season of Discovery", {
	[24814] = "green",
	[24821] = "yellow",
	[1213170] = {"blue","purple","yellow"},
	[1214002] = "red",
})

BigWigs:AddSounds("Lethon Season of Discovery", {
	[24814] = "info",
	[24821] = "alert",
	[1213170] = "warning",
	[1214002] = "long",
})

BigWigs:AddColors("Taerar Season of Discovery", {
	[24814] = "green",
	[1213170] = {"blue","purple","yellow"},
	[1214008] = "cyan",
	[1214028] = "orange",
})

BigWigs:AddSounds("Taerar Season of Discovery", {
	[24814] = "info",
	[1213170] = "warning",
	[1214008] = "long",
})

BigWigs:AddColors("Ysondre Season of Discovery", {
	[24795] = "cyan",
	[24814] = "green",
	[1213170] = {"blue","purple","yellow"},
	[1214136] = {"blue","orange"},
})

BigWigs:AddSounds("Ysondre Season of Discovery", {
	[24795] = "long",
	[24814] = "info",
	[1213170] = "warning",
	[1214136] = "warning",
})

BigWigs:AddColors("Balnazzar Scarlet Enclave", {
	[1231837] = {"blue","red"},
	[1231844] = {"blue","red"},
	[1231901] = "yellow",
	["berserk"] = {"orange","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Balnazzar Scarlet Enclave", {
	[1231837] = "alert",
	[1231844] = "warning",
	[1231901] = "info",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("High Commander Beatrix", {
	[1231873] = "blue",
	[1232389] = {"blue","purple"},
	[1232390] = {"blue","red"},
	[1232637] = {"blue","red"},
	[1237324] = "blue",
	["arrows"] = "yellow",
	["berserk"] = {"orange","red"},
	["bombing"] = "yellow",
	["meteor"] = "orange",
	["stages"] = "cyan",
	["waves"] = "yellow",
})

BigWigs:AddSounds("High Commander Beatrix", {
	[1231873] = "warning",
	[1232389] = "alarm",
	[1232637] = "warning",
	[1237324] = "underyou",
	["arrows"] = "info",
	["berserk"] = "alarm",
	["bombing"] = "info",
	["meteor"] = "alert",
	["stages"] = "long",
	["waves"] = "info",
})

BigWigs:AddColors("Solistrasza", {
	[1227696] = "red",
	[1228063] = {"blue","yellow"},
	[1231993] = {"blue","purple"},
	[1232097] = {"blue","orange"},
	["adds"] = "cyan",
	["berserk"] = {"orange","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Solistrasza", {
	[1227696] = "alarm",
	[1228063] = {"underyou","warning"},
	[1231993] = "alert",
	[1232097] = "warning",
	["adds"] = "info",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Alexei the Beastlord", {
	[1228295] = "red",
	[1230105] = "yellow",
	[1230200] = "blue",
	[1230242] = "blue",
	[1230899] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Alexei the Beastlord", {
	[1228295] = "alert",
	[1230105] = "warning",
	[1230200] = "info",
	[1230242] = "info",
	[1230899] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Mason the Echo", {
	[1229005] = {"blue","purple"},
	[1231585] = {"cyan","red"},
	[1231592] = {"green","orange"},
	[1234347] = {"green","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Mason the Echo", {
	[1229005] = "alarm",
	[1231585] = "long",
	[1231592] = "alert",
	[1234347] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Reborn Council", {
	[1231095] = {"green","orange"},
	[1231264] = "yellow",
	[1231282] = "cyan",
	[1231383] = "red",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Reborn Council", {
	[1231095] = "info",
	[1231264] = "warning",
	[1231282] = "long",
	[1231383] = "alarm",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Lillian Voss", {
	[1232192] = {"blue","purple"},
	[1233847] = "red",
	[1233849] = "blue",
	[1233883] = {"blue","green"},
	[1233901] = "blue",
	[1234540] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Lillian Voss", {
	[1233847] = "long",
	[1233849] = "alert",
	[1233883] = "warning",
	[1233901] = "alarm",
	[1234540] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Grand Crusader Caldoran", {
	[1229114] = "yellow",
	[1229272] = {"blue","yellow"},
	[1229503] = {"blue","purple"},
	[1229714] = "red",
	[1230697] = "cyan",
	[1231027] = "yellow",
	[1231618] = "orange",
	[1231651] = "orange",
	[1231654] = "orange",
	["berserk"] = {"orange","red"},
	["run"] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Grand Crusader Caldoran", {
	[1229114] = "alert",
	[1229272] = "alarm",
	[1229503] = "info",
	[1229714] = "warning",
	[1230697] = "alarm",
	[1231027] = "long",
	[1231618] = "alert",
	[1231651] = "alert",
	[1231654] = "alert",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Scarlet Enclave Trash", {
	["stages"] = "cyan",
})

BigWigs:AddSounds("Scarlet Enclave Trash", {
})
