-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lucifron", {
	[19702] = "red",
	[19703] = {"green","yellow"},
	[20604] = {"blue","orange"},
})

BigWigs:AddSounds("Lucifron", {
	[19702] = "long",
	[19703] = "info",
})

BigWigs:AddColors("Magmadar", {
	[19408] = "orange",
	[19428] = "blue",
	[19451] = {"green","yellow"},
	[461131] = "cyan",
})

BigWigs:AddSounds("Magmadar", {
	[19408] = "long",
	[19428] = "underyou",
	[19451] = "info",
	[461131] = "alert",
})

BigWigs:AddColors("Gehennas", {
	[19716] = {"green","orange"},
	[19717] = "blue",
})

BigWigs:AddSounds("Gehennas", {
	[19717] = "underyou",
})

BigWigs:AddColors("Garr", {
	[19492] = {"red","yellow"},
})

BigWigs:AddSounds("Garr", {
	[19492] = "info",
})

BigWigs:AddColors("Baron Geddon", {
	[19659] = {"green","yellow"},
	[19695] = "red",
	[20475] = {"blue","orange","red"},
	[20478] = "orange",
	[461103] = "blue",
})

BigWigs:AddSounds("Baron Geddon", {
	[19659] = "info",
	[19695] = "alarm",
	[20475] = "warning",
	[20478] = "long",
	[461103] = "underyou",
})

BigWigs:AddColors("Shazzrah", {
	[19713] = "yellow",
	[19714] = {"green","orange"},
	[19715] = "yellow",
	[23138] = "red",
	[460856] = {"green","red"},
})

BigWigs:AddSounds("Shazzrah", {
	[19713] = "alarm",
	[19714] = "alarm",
	[19715] = "alert",
	[23138] = "long",
	[460856] = {"info","warning"},
})

BigWigs:AddColors("Sulfuron Harbinger", {
	[19775] = "red",
	[19778] = "orange",
	[19779] = "yellow",
	[461103] = "blue",
})

BigWigs:AddSounds("Sulfuron Harbinger", {
	[19775] = "alert",
	[19778] = "alarm",
	[19779] = "info",
	[461103] = "underyou",
})

BigWigs:AddColors("Golemagg the Incinerator", {
	[13880] = {"blue","purple"},
	[20228] = {"blue","orange"},
	[460858] = {"blue","orange"},
	[461463] = "red",
})

BigWigs:AddSounds("Golemagg the Incinerator", {
	[13880] = "alert",
	[460858] = "alarm",
	[461463] = "warning",
})

BigWigs:AddColors("Majordomo Executus", {
	[20534] = {"blue","yellow"},
	[20619] = "red",
	[21075] = "yellow",
	[364895] = "orange",
	[364908] = "orange",
	[461056] = {"blue","red"},
})

BigWigs:AddSounds("Majordomo Executus", {
	[20619] = "info",
	[21075] = "info",
	[364895] = "alert",
	[364908] = "alert",
	[461056] = "warning",
})

BigWigs:AddColors("Ragnaros Classic", {
	[20566] = "red",
	[461062] = "blue",
	["adds"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ragnaros Classic", {
	[20566] = "info",
	[461062] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("The Molten Core", {
	[460883] = "red",
	[460885] = "red",
	[460887] = "orange",
	[460895] = {"blue","yellow"},
	[460898] = {"blue","yellow"},
	["adds"] = "cyan",
})

BigWigs:AddSounds("The Molten Core", {
	[460883] = "alert",
	[460885] = "long",
	[460887] = "alarm",
	[460895] = "warning",
	[460898] = "warning",
	["adds"] = "info",
})

BigWigs:AddColors("Razorgore the Untamed", {
	[14515] = {"blue","red"},
	[23023] = {"blue","orange"},
	[366909] = "blue",
	[367740] = "blue",
	[367873] = "blue",
	["adds"] = "cyan",
	["eggs"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Razorgore the Untamed", {
	[14515] = "alert",
	[23023] = "info",
	[366909] = "underyou",
	[367740] = "alarm",
	[367873] = "underyou",
	["adds"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Vaelastrasz the Corrupt", {
	[18173] = {"blue","yellow"},
	[23620] = {"blue","purple"},
})

BigWigs:AddSounds("Vaelastrasz the Corrupt", {
	[18173] = "warning",
	[23620] = {"long","warning"},
})

BigWigs:AddColors("Broodlord Lashlayer", {
	[18670] = {"blue","yellow"},
	[23331] = "orange",
	[24573] = {"blue","purple"},
	[367369] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Broodlord Lashlayer", {
	[18670] = "alert",
	[23331] = "info",
	[24573] = "alarm",
	[367369] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Firemaw", {
	[22539] = "red",
	[23339] = "yellow",
	[23341] = "blue",
	[366305] = "blue",
})

BigWigs:AddSounds("Firemaw", {
	[22539] = "long",
	[23339] = "info",
	[23341] = "warning",
	[366305] = "warning",
})

BigWigs:AddColors("Ebonroc", {
	[22539] = "red",
	[23339] = "yellow",
	[23340] = {"blue","purple"},
	[368515] = "blue",
})

BigWigs:AddSounds("Ebonroc", {
	[22539] = "long",
	[23339] = "info",
	[23340] = "alarm",
	[368515] = "alert",
})

BigWigs:AddColors("Flamegor", {
	[22539] = "red",
	[23339] = "yellow",
	[23342] = {"green","orange"},
	[368521] = "blue",
	[467732] = "blue",
	[467764] = "blue",
})

BigWigs:AddSounds("Flamegor", {
	[22539] = "long",
	[23339] = "info",
	[23342] = "alarm",
	[368521] = "alert",
	[467732] = "warning",
	[467764] = "warning",
})

BigWigs:AddColors("Chromaggus", {
	[23128] = {"green","orange"},
	[23170] = "blue",
	[23174] = "red",
	[23537] = "red",
	[468195] = "cyan",
	["breath"] = "yellow",
	["vulnerability"] = {"green","red"},
})

BigWigs:AddSounds("Chromaggus", {
	[23128] = "alarm",
	[23174] = "warning",
	[468195] = "long",
	["breath"] = "long",
	["vulnerability"] = {"info","warning"},
})

BigWigs:AddColors("Nefarian Classic", {
	[22539] = "yellow",
	[22667] = {"blue","yellow"},
	[22686] = "red",
	[22687] = {"blue","green","yellow"},
	["add"] = "green",
	["classcall"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nefarian Classic", {
	[22539] = "alarm",
	[22667] = "warning",
	[22686] = "alert",
	[22687] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Blackwing Lair Trash", {
	[19717] = "blue",
	[22291] = {"blue","orange"},
	[369330] = "blue",
	[466357] = {"blue","orange"},
	[466435] = {"blue","orange"},
	["target_vulnerability"] = {"red","yellow"},
})

BigWigs:AddSounds("Blackwing Lair Trash", {
	[19717] = "underyou",
	[22291] = "warning",
	[369330] = "underyou",
	[466357] = "warning",
	[466435] = "warning",
})

BigWigs:AddColors("Kurinnaxx", {
	[25646] = {"blue","purple"},
	[25648] = {"blue","orange"},
	[26527] = {"green","red"},
})

BigWigs:AddSounds("Kurinnaxx", {
	[25646] = "warning",
	[25648] = "alert",
	[26527] = "long",
})

BigWigs:AddColors("General Rajaxx", {
	[8269] = "red",
	[25462] = {"green","orange"},
	[25471] = {"blue","yellow"},
	[25599] = "orange",
	[26550] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("General Rajaxx", {
	[8269] = "long",
	[25462] = "alarm",
	[25471] = "warning",
	[25599] = "alert",
	[26550] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("Moam", {
	[25685] = {"red","yellow"},
})

BigWigs:AddSounds("Moam", {
	[25685] = "long",
})

BigWigs:AddColors("Buru the Gorger", {
	["fixate"] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Buru the Gorger", {
	["fixate"] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Ayamiss the Hunter", {
	[8269] = {"green","red"},
	[17742] = "blue",
	[25725] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ayamiss the Hunter", {
	[17742] = "underyou",
	[25725] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Ossirian the Unscarred", {
	[25176] = "red",
	[25177] = "yellow",
	[25178] = "yellow",
	[25180] = "yellow",
	[25181] = "yellow",
	[25183] = "yellow",
	[25188] = "orange",
	[25189] = {"blue","red"},
	[25195] = "orange",
})

BigWigs:AddSounds("Ossirian the Unscarred", {
	[25176] = "alert",
	[25177] = "info",
	[25178] = "info",
	[25180] = "info",
	[25181] = "info",
	[25183] = "info",
	[25189] = "warning",
	[25195] = "long",
})

BigWigs:AddColors("Ruins of Ahn'Qiraj Trash", {
	[8269] = "red",
	[8732] = "orange",
	[14297] = "red",
	[17430] = "green",
	[17431] = "green",
	[22997] = {"blue","yellow"},
	[24340] = "red",
	[25698] = "orange",
	[1214956] = "yellow",
	[1215202] = "blue",
	[1215421] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ruins of Ahn'Qiraj Trash", {
	[8269] = "long",
	[8732] = "alert",
	[14297] = "alarm",
	[22997] = "warning",
	[24340] = "info",
	[25698] = "long",
	[1215202] = "warning",
	[1215421] = "underyou",
})

BigWigs:AddColors("The Prophet Skeram", {
	[747] = "cyan",
	[785] = {"blue","yellow"},
	[20449] = "red",
	[26192] = "orange",
})

BigWigs:AddSounds("The Prophet Skeram", {
	[747] = "info",
	[785] = "alert",
	[20449] = "alert",
})

BigWigs:AddColors("Silithid Royalty", {
	[25786] = "blue",
	[25807] = {"green","orange"},
	[25812] = "yellow",
	[26580] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Silithid Royalty", {
	[25786] = "underyou",
	[25807] = "alert",
	[25812] = "info",
	[26580] = "long",
})

BigWigs:AddColors("Battleguard Sartura", {
	[8269] = "orange",
	[26083] = {"green","red"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Battleguard Sartura", {
	[8269] = "long",
	[26083] = "warning",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Fankriss the Unyielding", {
	[720] = {"blue","red"},
	[25646] = {"blue","purple"},
	[25832] = "cyan",
})

BigWigs:AddSounds("Fankriss the Unyielding", {
	[720] = "alarm",
	[25646] = "alert",
	[25832] = "warning",
})

BigWigs:AddColors("Viscidus", {
	[25989] = "blue",
	[25991] = "yellow",
	["freeze"] = {"green","orange","red"},
})

BigWigs:AddSounds("Viscidus", {
	[25989] = "underyou",
})

BigWigs:AddColors("Princess Huhuran", {
	[26051] = {"green","yellow"},
	[26180] = {"green","red"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Princess Huhuran", {
	[26051] = "alarm",
	[26180] = "alert",
	["berserk"] = {"alarm","long"},
})

BigWigs:AddColors("The Twin Emperors", {
	[800] = "orange",
	[802] = "yellow",
	[804] = "red",
	[7393] = "red",
	[26607] = "blue",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("The Twin Emperors", {
	[800] = "alert",
	[802] = "info",
	[804] = "alarm",
	[7393] = "warning",
	[26607] = "underyou",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Ouro", {
	[26102] = "red",
	[26103] = "orange",
	[26615] = {"green","yellow"},
	[1215744] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ouro", {
	[26102] = "alert",
	[26103] = "alarm",
	[26615] = "info",
	[1215744] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("C'Thun", {
	[26029] = {"orange","red"},
	[26134] = "blue",
	[26476] = "blue",
	["eye_tentacles"] = "red",
	["giant_claw_tentacle"] = "red",
	["giant_eye_tentacle"] = "red",
	["stages"] = "cyan",
	["weakened"] = "green",
})

BigWigs:AddSounds("C'Thun", {
	[26134] = "warning",
	[26476] = "warning",
	["eye_tentacles"] = "alarm",
	["giant_claw_tentacle"] = "alert",
	["giant_eye_tentacle"] = "warning",
	["stages"] = {"alert","long"},
	["weakened"] = "long",
})

BigWigs:AddColors("Ahn'Qiraj Trash", {
	[8269] = "red",
	[8599] = "red",
	[17430] = "green",
	[17431] = "green",
	[25051] = {"blue","purple"},
	[25698] = "orange",
	[26079] = {"blue","yellow"},
	[26554] = "orange",
	[26555] = "red",
	[26556] = {"blue","yellow"},
	[26558] = "red",
	[26565] = "orange",
	[1214956] = "yellow",
	[1215202] = "blue",
	[1215421] = "blue",
	["stages"] = "cyan",
	["target_buffs"] = {"red","yellow"},
})

BigWigs:AddSounds("Ahn'Qiraj Trash", {
	[8269] = "long",
	[25698] = "long",
	[26079] = "alert",
	[26554] = "alert",
	[26555] = "alarm",
	[26556] = "warning",
	[26558] = "info",
	[26565] = "info",
	[1215202] = "warning",
	[1215421] = "underyou",
})

BigWigs:AddColors("High Priestess Jeklik", {
	[12097] = {"blue","purple"},
	[16098] = {"green","red"},
	[23952] = {"blue","orange"},
	[23953] = {"green","yellow"},
	[23954] = {"green","red"},
	[23970] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Priestess Jeklik", {
	[16098] = "warning",
	[23953] = "alert",
	[23954] = "warning",
	[23970] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("High Priest Venoxis", {
	[8269] = "orange",
	[23860] = "yellow",
	[23861] = {"blue","red"},
	[23865] = {"blue","yellow"},
	[23895] = {"green","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Priest Venoxis", {
	[8269] = "long",
	[23861] = {"alarm","underyou"},
	[23895] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("High Priestess Mar'li", {
	[24083] = "yellow",
	[24099] = "yellow",
	[24300] = {"blue","orange"},
})

BigWigs:AddSounds("High Priestess Mar'li", {
	[24083] = "info",
	[24099] = "alarm",
	[24300] = "alert",
})

BigWigs:AddColors("High Priest Thekal", {
	[8269] = "red",
	[12540] = {"blue","purple"},
	[21060] = {"blue","purple"},
	[22666] = {"blue","yellow"},
	[22859] = {"blue","purple"},
	[24183] = "yellow",
	[24185] = "orange",
	[24189] = "orange",
	[24208] = "red",
})

BigWigs:AddSounds("High Priest Thekal", {
	[8269] = "alarm",
	[12540] = "warning",
	[21060] = "warning",
	[22666] = "alert",
	[22859] = "alarm",
	[24183] = "info",
	[24185] = "alert",
	[24208] = "alert",
})

BigWigs:AddColors("High Priestess Arlokk", {
	[12540] = {"blue","purple"},
	[24210] = {"blue","red"},
	[24212] = {"blue","orange"},
})

BigWigs:AddSounds("High Priestess Arlokk", {
	[12540] = "warning",
	[24210] = "alarm",
	[24212] = "alert",
})

BigWigs:AddColors("Hakkar", {
	[24324] = {"orange","red"},
	[24327] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Hakkar", {
	[24324] = {"alarm","long"},
	[24327] = "info",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Bloodlord Mandokir", {
	[16856] = {"blue","purple"},
	[24314] = {"blue","yellow"},
	[24318] = {"blue","red"},
})

BigWigs:AddSounds("Bloodlord Mandokir", {
	[16856] = "warning",
	[24314] = "info",
	[24318] = "alarm",
})

BigWigs:AddColors("Jin'do the Hexxer", {
	[17172] = {"blue","purple"},
	[24262] = "red",
	[24306] = {"blue","yellow"},
	[24309] = "orange",
	[24466] = {"blue","yellow"},
})

BigWigs:AddSounds("Jin'do the Hexxer", {
	[17172] = "alert",
	[24262] = "warning",
	[24306] = "alarm",
	[24309] = "info",
	[24466] = "long",
})

BigWigs:AddColors("Gahz'ranka", {
	[21099] = "yellow",
	[22421] = "orange",
})

BigWigs:AddSounds("Gahz'ranka", {
	[21099] = "info",
	[22421] = "alarm",
})

BigWigs:AddColors("Edge of Madness", {
	[24646] = "orange",
	[24699] = "orange",
	[24729] = "orange",
	[26550] = "yellow",
})

BigWigs:AddSounds("Edge of Madness", {
	[24646] = "alarm",
	[24699] = "alert",
	[24729] = "alarm",
	[26550] = "info",
})

BigWigs:AddColors("Patchwerk", {
	[28131] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Patchwerk", {
	[28131] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Grobbulus", {
	[28169] = {"blue","red"},
	[28240] = "yellow",
	["adds"] = "orange",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Grobbulus", {
	[28169] = "warning",
	[28240] = "info",
	["adds"] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Gluth", {
	[25646] = {"blue","purple"},
	[28371] = {"green","orange"},
	[28375] = "red",
	[29306] = "blue",
	[29685] = "yellow",
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Gluth", {
	[25646] = "info",
	[28371] = "alert",
	[28375] = "warning",
	[29685] = "long",
	["berserk"] = "alarm",
})

BigWigs:AddColors("Thaddius", {
	[28059] = "blue",
	[28084] = "blue",
	[28089] = "orange",
	[28134] = "red",
	[28338] = "red",
	["berserk"] = {"orange","red"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Thaddius", {
	[28059] = "warning",
	[28084] = "warning",
	[28089] = "long",
	[28338] = "alert",
	["berserk"] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Noth the Plaguebringer", {
	[29208] = "yellow",
	[29212] = "blue",
	[29213] = {"green","red"},
	[29214] = "red",
	["adds"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Noth the Plaguebringer", {
	[29208] = "alert",
	[29213] = "warning",
	[29214] = "alarm",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Heigan the Unclean", {
	[29998] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Heigan the Unclean", {
	[29998] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Loatheb", {
	[29184] = "blue",
	[29204] = "red",
	[29232] = "blue",
	[29234] = "red",
	[29865] = "yellow",
	[30281] = "orange",
	[1225419] = "blue",
})

BigWigs:AddSounds("Loatheb", {
	[29184] = "long",
	[29204] = "warning",
	[29234] = "info",
	[30281] = "alert",
	[1225419] = "long",
})

BigWigs:AddColors("Anub'Rekhan", {
	[28783] = {"blue","yellow"},
	[28785] = {"green","orange","red","yellow"},
})

BigWigs:AddSounds("Anub'Rekhan", {
	[28783] = {"alert","warning"},
	[28785] = {"info","long"},
})

BigWigs:AddColors("Grand Widow Faerlina", {
	[28732] = "yellow",
	[28794] = "blue",
	[28796] = "orange",
	[28798] = {"green","red"},
	[30225] = "blue",
})

BigWigs:AddSounds("Grand Widow Faerlina", {
	[28732] = "info",
	[28794] = "underyou",
	[28796] = "alert",
	[28798] = "warning",
})

BigWigs:AddColors("Maexxna", {
	[28622] = {"blue","yellow"},
	[28747] = "orange",
	[28776] = {"blue","green","purple"},
	[29484] = "red",
	["adds"] = "yellow",
})

BigWigs:AddSounds("Maexxna", {
	[28622] = "alert",
	[28747] = "warning",
	[28776] = "info",
	[29484] = "long",
})

BigWigs:AddColors("Instructor Razuvious", {
	[29060] = "orange",
	[29061] = "yellow",
	[29107] = "red",
})

BigWigs:AddSounds("Instructor Razuvious", {
	[29060] = "info",
	[29061] = "long",
	[29107] = "warning",
})

BigWigs:AddColors("Gothik the Harvester", {
	["add_death"] = "green",
	["adds"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Gothik the Harvester", {
	["stages"] = {"info","long"},
})

BigWigs:AddColors("The Four Horsemen", {
	[28863] = {"blue","orange"},
	[28883] = "yellow",
	[28884] = "red",
	[29061] = "yellow",
	["mark"] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Four Horsemen", {
	[28863] = {"alarm","underyou"},
	[28883] = "alert",
	[28884] = "info",
	[29061] = "long",
	["mark"] = "warning",
})

BigWigs:AddColors("Sapphiron", {
	[28522] = {"blue","yellow"},
	[28524] = "red",
	[28542] = {"green","orange"},
	[28547] = "blue",
	[1219728] = {"blue","yellow"},
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Sapphiron", {
	[28524] = "warning",
	[28542] = "alert",
	[28547] = "underyou",
	[1219728] = "warning",
	["berserk"] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Kel'Thuzad", {
	[27808] = {"blue","yellow"},
	[27810] = {"blue","red"},
	[27819] = {"blue","yellow"},
	[28410] = {"blue","orange"},
	[28467] = {"blue","purple"},
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kel'Thuzad", {
	[27808] = "alert",
	[27810] = "warning",
	[27819] = "warning",
	[28410] = "long",
	["adds"] = "info",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Naxxramas Trash", {
	[1219235] = {"blue","yellow"},
})

BigWigs:AddSounds("Naxxramas Trash", {
	[1219235] = "warning",
})

BigWigs:AddColors("Onyxia", {
	[17086] = "red",
	[18392] = {"blue","yellow"},
	[18431] = "yellow",
	[18435] = "orange",
	[18958] = {"blue","purple"},
	[364849] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Onyxia", {
	[17086] = "warning",
	[18392] = "alarm",
	[18431] = "info",
	[18435] = "alert",
	[364849] = "alert",
	["stages"] = "long",
})
