-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Balnazzar", {
	[1231837] = {"blue","orange","red"},
	[1231844] = {"blue","red"},
	[1231901] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Balnazzar", {
	[1231837] = {"alert","warning"},
	[1231844] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("High Commander Beatrix", {
	[1232390] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Commander Beatrix", {
	[1232390] = "warning",
})

BigWigs:AddColors("Solistrasza", {
	[1227696] = "red",
	[1228063] = {"blue","yellow"},
	[1231993] = {"blue","purple"},
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Solistrasza", {
	[1227696] = "alarm",
	[1228063] = {"underyou","warning"},
	[1231993] = "alert",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Alexei the Beastlord", {
	[1228295] = "red",
	[1230105] = "orange",
	[1230200] = "blue",
	[1230242] = "blue",
})

BigWigs:AddSounds("Alexei the Beastlord", {
	[1228295] = "alert",
	[1230105] = "alarm",
	[1230200] = "info",
	[1230242] = "info",
})

BigWigs:AddColors("Mason the Echo", {
	[1229005] = {"blue","purple"},
	[1231585] = {"cyan","red"},
	[1231592] = {"green","orange"},
	[1234347] = {"green","yellow"},
})

BigWigs:AddSounds("Mason the Echo", {
	[1229005] = "alarm",
	[1231585] = "long",
	[1231592] = "alert",
	[1234347] = "info",
})

BigWigs:AddColors("Reborn Council", {
	[1231010] = "blue",
	[1231095] = {"green","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Reborn Council", {
	[1231010] = "warning",
	[1231095] = "info",
})

BigWigs:AddColors("Lillian Voss", {
	[1232192] = {"blue","orange"},
	[1233847] = "red",
	[1233849] = "blue",
	[1233883] = {"blue","green"},
	[1233901] = "blue",
	[1234540] = "yellow",
})

BigWigs:AddSounds("Lillian Voss", {
	[1233847] = "long",
	[1233849] = "alert",
	[1233883] = "warning",
	[1233901] = "alarm",
	[1234540] = "info",
})

BigWigs:AddColors("Grand Crusader Caldoran", {
	[1229114] = "yellow",
	[1229272] = {"blue","orange"},
	[1229503] = {"blue","purple"},
	[1229714] = "red",
})

BigWigs:AddSounds("Grand Crusader Caldoran", {
	[1229114] = "long",
	[1229272] = "alarm",
	[1229503] = "info",
	[1229714] = "warning",
})
